name: Release KMP Library

on:
  release:
    types: [ published ]

jobs:
  release:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Write gradle.properties
        run: |
          mkdir -p ~/.gradle
          echo "${{ secrets.GRADLE_PROPERTIES }}" | base64 -d > ~/.gradle/gradle.properties
      - name: Update permissions
        working-directory: .
        run: chmod +x ./gradlew ./.github/scripts/*.sh
      - name: Check version
        working-directory: .
        run: ./.github/scripts/check_version.sh $(echo "${{ github.ref }}" | sed -e "s,^refs/tags/,,")
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build and Release
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          ./gradlew build test -Pversion=$VERSION dokkaHtml publish --info
      - name: Prepare Javadoc locally
        working-directory: .
        run: ./.github/scripts/prepare_javadoc.sh $(echo "${{ github.ref }}" | sed -e "s,^refs/tags/,,")
      - name: Deploy Dokka to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/dokka
          enable_jekyll: true