name: Publish KMP Library

on:
  push:
    branches: [ main ]
  workflow_dispatch: # Triggered manually

jobs:
  publish:
    runs-on: macos-latest 
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Write gradle.properties
        run: |
          mkdir -p ~/.gradle
          echo "${{ secrets.GRADLE_PROPERTIES }}" | base64 -d > ~/.gradle/gradle.properties
      - name: Update permissions
        working-directory: .
        run: chmod +x ./gradlew ./.github/scripts/*.sh
      - name: Check version
        working-directory: .
        run: ./.github/scripts/check_version.sh
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Build and Publish
        run: ./gradlew build test publish dokkaHtml --info
      - name: Prepare Dokka doc locally
        working-directory: .
        run: ./.github/scripts/prepare_dokkadoc.sh
      - name: Deploy Dokka to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/dokka
          enable_jekyll: true